# Generated by Django 2.2.5 on 2022-01-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20220114_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
